package br.maybueno.view;

import br.maybueno.controller.JardimController;
import br.maybueno.controller.PlantaController;
import br.maybueno.dao.JardimDAO;
import br.maybueno.dao.PlantaDAO;
import br.maybueno.model.JardimModel;
import br.maybueno.model.PlantaModel;

/**
 *
 * @author MayBueno
 */
public class JardimTela extends javax.swing.JFrame {

    private JardimController controller = new JardimController();
    private PlantaModel p = new PlantaModel();
    public JardimModel j = new JardimModel();
    private JardimDAO dao = new JardimDAO();
    
    /**
     * Creates new form JardimTela
     */
    public JardimTela(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        BabiloniaPersistenciaEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("BabiloniaPersistencia").createEntityManager();
        jardimModelQuery = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT j FROM JardimModel j");
        jardimModelList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : jardimModelQuery.getResultList();
        plantaQuery = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery.getResultList();
        plantaQuery1 = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery1.getResultList();
        plantaQuery2 = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery2.getResultList();
        jardimModelQuery1 = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT j FROM JardimModel j");
        jardimModelList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : jardimModelQuery1.getResultList();
        jardimModelQuery2 = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT j FROM JardimModel j");
        jardimModelList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : jardimModelQuery2.getResultList();
        PainelGuias = new javax.swing.JTabbedPane();
        abaCadastrar = new javax.swing.JPanel();
        lPosicao = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPosicao = new javax.swing.JTextField();
        lNome = new javax.swing.JLabel();
        bt1 = new javax.swing.JLabel();
        bt2 = new javax.swing.JLabel();
        lSalvar = new javax.swing.JLabel();
        lFundo = new javax.swing.JLabel();
        abaAlterar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAlterar = new javax.swing.JTable();
        painelTXT = new javax.swing.JPanel();
        txtIdPlanta = new javax.swing.JTextField();
        txtAlterarNome = new javax.swing.JTextField();
        txtAlterarPosicao = new javax.swing.JTextField();
        txtAlterarPlantas = new javax.swing.JTextField();
        lAtualizar = new javax.swing.JLabel();
        abaExcluir = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExcluir = new javax.swing.JTable();
        lExcluir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtIdJardimExcluir = new javax.swing.JTextField();
        lHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 840));
        getContentPane().setLayout(null);

        abaCadastrar.setLayout(null);

        lPosicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPosicao.setText("Posição do jardim (referência):");
        abaCadastrar.add(lPosicao);
        lPosicao.setBounds(180, 340, 260, 16);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        abaCadastrar.add(txtNome);
        txtNome.setBounds(200, 240, 220, 30);
        abaCadastrar.add(txtPosicao);
        txtPosicao.setBounds(200, 360, 220, 30);

        lNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNome.setText("Nome da jardim:");
        abaCadastrar.add(lNome);
        lNome.setBounds(170, 220, 290, 20);

        bt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/btPreencher.png"))); // NOI18N
        abaCadastrar.add(bt1);
        bt1.setBounds(0, 160, 560, 120);

        bt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/btPreencher.png"))); // NOI18N
        abaCadastrar.add(bt2);
        bt2.setBounds(0, 280, 560, 120);

        lSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/salvar.png"))); // NOI18N
        lSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSalvarMouseClicked(evt);
            }
        });
        abaCadastrar.add(lSalvar);
        lSalvar.setBounds(440, 520, 100, 90);

        lFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/bg07.png"))); // NOI18N
        abaCadastrar.add(lFundo);
        lFundo.setBounds(0, 0, 560, 630);

        PainelGuias.addTab("Cadastrar", abaCadastrar);

        abaAlterar.setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jardimModelList1, jTableAlterar);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idJardim}"));
        columnBinding.setColumnName("Id Jardim");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${posicao}"));
        columnBinding.setColumnName("Posicao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${plantas}"));
        columnBinding.setColumnName("Plantas");
        columnBinding.setColumnClass(java.util.List.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane3.setViewportView(jTableAlterar);

        abaAlterar.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 560, 470);

        painelTXT.setLayout(new java.awt.GridLayout(1, 0));

        txtIdPlanta.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAlterar, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idJardim}"), txtIdPlanta, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        painelTXT.add(txtIdPlanta);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAlterar, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), txtAlterarNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        painelTXT.add(txtAlterarNome);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAlterar, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.posicao}"), txtAlterarPosicao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        painelTXT.add(txtAlterarPosicao);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAlterar, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.plantas}"), txtAlterarPlantas, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        painelTXT.add(txtAlterarPlantas);

        abaAlterar.add(painelTXT);
        painelTXT.setBounds(0, 470, 560, 40);

        lAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/salvar.png"))); // NOI18N
        lAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAtualizarMouseClicked(evt);
            }
        });
        abaAlterar.add(lAtualizar);
        lAtualizar.setBounds(450, 510, 110, 120);

        PainelGuias.addTab("Alterar", abaAlterar);

        abaExcluir.setLayout(null);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jardimModelList2, jTableExcluir);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idJardim}"));
        columnBinding.setColumnName("Id Jardim");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${posicao}"));
        columnBinding.setColumnName("Posicao");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTableExcluir);

        abaExcluir.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 560, 470);

        lExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/salvar.png"))); // NOI18N
        lExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lExcluirMouseClicked(evt);
            }
        });
        abaExcluir.add(lExcluir);
        lExcluir.setBounds(450, 500, 100, 130);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        txtIdJardimExcluir.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableExcluir, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idJardim}"), txtIdJardimExcluir, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(txtIdJardimExcluir);

        abaExcluir.add(jPanel1);
        jPanel1.setBounds(0, 470, 560, 40);

        PainelGuias.addTab("Excluir", abaExcluir);

        getContentPane().add(PainelGuias);
        PainelGuias.setBounds(0, 140, 570, 660);

        lHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/bt_Jardim.png"))); // NOI18N
        getContentPane().add(lHeader);
        lHeader.setBounds(0, 0, 570, 140);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    // BORBOLETA -- SALVAR
    private void lSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSalvarMouseClicked
        
        String nome = this.txtNome.getText();
        String posicao = this.txtPosicao.getText();
        this.controller.cadastrarJardim(nome, posicao);
        
    }//GEN-LAST:event_lSalvarMouseClicked

    // BORBOLETA -- ATUALIZAR
    private void lAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAtualizarMouseClicked
        
        String nome, posicao; int idJ;
            nome = this.txtAlterarNome.getText();
            posicao = this.txtAlterarPosicao.getText();
            idJ = Integer.parseInt(this.txtIdPlanta.getText()); 
          
        this.controller.atualizarJardim(nome, posicao, idJ);
        
    }//GEN-LAST:event_lAtualizarMouseClicked

    // BORBOLETA -- EXCLUIR
    private void lExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lExcluirMouseClicked
       
        int idJ;      
        idJ = Integer.parseInt(this.txtIdJardimExcluir.getText());
        
        this.controller.removerJardim(idJ);
        
        txtIdJardimExcluir.setText("Excluído");
        
    }//GEN-LAST:event_lExcluirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JardimTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JardimTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JardimTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JardimTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JardimTela dialog = new JardimTela(new javax.swing.JFrame(), true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager BabiloniaPersistenciaEntityManager;
    private javax.swing.JTabbedPane PainelGuias;
    private javax.swing.JPanel abaAlterar;
    private javax.swing.JPanel abaCadastrar;
    private javax.swing.JPanel abaExcluir;
    private javax.swing.JLabel bt1;
    private javax.swing.JLabel bt2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAlterar;
    private javax.swing.JTable jTableExcluir;
    private java.util.List<br.maybueno.model.JardimModel> jardimModelList;
    private java.util.List<br.maybueno.model.JardimModel> jardimModelList1;
    private java.util.List<br.maybueno.model.JardimModel> jardimModelList2;
    private javax.persistence.Query jardimModelQuery;
    private javax.persistence.Query jardimModelQuery1;
    private javax.persistence.Query jardimModelQuery2;
    private javax.swing.JLabel lAtualizar;
    private javax.swing.JLabel lExcluir;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel lHeader;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPosicao;
    private javax.swing.JLabel lSalvar;
    private javax.swing.JPanel painelTXT;
    private java.util.List<br.maybueno.view.Planta> plantaList;
    private java.util.List<br.maybueno.view.Planta> plantaList1;
    private java.util.List<br.maybueno.view.Planta> plantaList2;
    private javax.persistence.Query plantaQuery;
    private javax.persistence.Query plantaQuery1;
    private javax.persistence.Query plantaQuery2;
    private javax.swing.JTextField txtAlterarNome;
    private javax.swing.JTextField txtAlterarPlantas;
    private javax.swing.JTextField txtAlterarPosicao;
    private javax.swing.JTextField txtIdJardimExcluir;
    private javax.swing.JTextField txtIdPlanta;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPosicao;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
