package br.maybueno.view;

import br.maybueno.controller.PlantaController;
import br.maybueno.dao.PlantaDAO;
import br.maybueno.model.JardimModel;
import br.maybueno.model.PlantaModel;

/**
 *
 * @author MayBueno
 */
public class PlantaTela extends javax.swing.JFrame {

    private PlantaController controller = new PlantaController();
    private PlantaModel p = new PlantaModel();
    public PlantaModel plantaAlterada = new PlantaModel();
    private PlantaDAO dao = new PlantaDAO();
    private int idPlantaAlterar;
    
    /**
     * Creates new form JardimTela
     */
    public PlantaTela(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        BabiloniaPersistenciaEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("BabiloniaPersistencia").createEntityManager();
        jardimModelQuery = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT j FROM JardimModel j");
        jardimModelList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : jardimModelQuery.getResultList();
        plantaQuery = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery.getResultList();
        plantaQuery1 = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery1.getResultList();
        plantaQuery2 = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery2.getResultList();
        plantaQuery3 = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery3.getResultList();
        PainelGuias = new javax.swing.JTabbedPane();
        abaCadastrar = new javax.swing.JPanel();
        lTamanho = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTamanho = new javax.swing.JTextField();
        comboxStatus = new javax.swing.JComboBox<>();
        comboxJardim = new javax.swing.JComboBox<>();
        lNome = new javax.swing.JLabel();
        lStatus = new javax.swing.JLabel();
        lJardim = new javax.swing.JLabel();
        bt1 = new javax.swing.JLabel();
        bt2 = new javax.swing.JLabel();
        bt3 = new javax.swing.JLabel();
        bt4 = new javax.swing.JLabel();
        lSalvar = new javax.swing.JLabel();
        lFundo = new javax.swing.JLabel();
        abaAlterar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAlterar = new javax.swing.JTable();
        painelTXT = new javax.swing.JPanel();
        comboxAlterarIdJardim = new javax.swing.JComboBox<>();
        txtIdPlanta = new javax.swing.JTextField();
        txtAlterarNome = new javax.swing.JTextField();
        txtAlterarTamanho = new javax.swing.JTextField();
        txtAlterarStatus = new javax.swing.JTextField();
        lAtualizar = new javax.swing.JLabel();
        lMorte = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtExcluirIdPlanta = new javax.swing.JTextField();
        comboxExcluirJardim = new javax.swing.JComboBox<>();
        txtExcluirNome = new javax.swing.JTextField();
        txtExcluirTamanho = new javax.swing.JTextField();
        abaExcluir = new javax.swing.JPanel();
        lListar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaLista = new javax.swing.JTextArea();
        lHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 840));
        getContentPane().setLayout(null);

        abaCadastrar.setLayout(null);

        lTamanho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTamanho.setText("Tamanho atual da planta:");
        abaCadastrar.add(lTamanho);
        lTamanho.setBounds(180, 340, 260, 16);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        abaCadastrar.add(txtNome);
        txtNome.setBounds(200, 240, 220, 30);
        abaCadastrar.add(txtTamanho);
        txtTamanho.setBounds(240, 360, 140, 22);

        comboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feliz", "Satisfeita", "Triste", "Doente", "Apática", "Morta" }));
        abaCadastrar.add(comboxStatus);
        comboxStatus.setBounds(210, 480, 190, 22);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jardimModelList, comboxJardim);
        bindingGroup.addBinding(jComboBoxBinding);

        abaCadastrar.add(comboxJardim);
        comboxJardim.setBounds(224, 130, 180, 22);

        lNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNome.setText("Nome da planta:");
        abaCadastrar.add(lNome);
        lNome.setBounds(170, 220, 290, 20);

        lStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lStatus.setText("Status:");
        abaCadastrar.add(lStatus);
        lStatus.setBounds(210, 460, 190, 16);

        lJardim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lJardim.setText("Jardim");
        abaCadastrar.add(lJardim);
        lJardim.setBounds(170, 110, 300, 16);

        bt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/btPreencher.png"))); // NOI18N
        abaCadastrar.add(bt1);
        bt1.setBounds(0, 160, 560, 120);

        bt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/btPreencher.png"))); // NOI18N
        abaCadastrar.add(bt2);
        bt2.setBounds(0, 280, 560, 120);

        bt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/btPreencher.png"))); // NOI18N
        abaCadastrar.add(bt3);
        bt3.setBounds(0, 400, 560, 120);

        bt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/btPreencher.png"))); // NOI18N
        abaCadastrar.add(bt4);
        bt4.setBounds(0, 20, 560, 170);

        lSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/salvar.png"))); // NOI18N
        lSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSalvarMouseClicked(evt);
            }
        });
        abaCadastrar.add(lSalvar);
        lSalvar.setBounds(440, 520, 100, 90);

        lFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/bg02.png"))); // NOI18N
        abaCadastrar.add(lFundo);
        lFundo.setBounds(0, 0, 560, 630);

        PainelGuias.addTab("Cadastrar", abaCadastrar);

        abaAlterar.setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, plantaList1, jTableAlterar);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idJardim}"));
        columnBinding.setColumnName("Id Jardim");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idPlanta}"));
        columnBinding.setColumnName("Id Planta");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tamanhoAtual}"));
        columnBinding.setColumnName("Tamanho Atual");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${status}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane3.setViewportView(jTableAlterar);

        abaAlterar.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 560, 470);

        painelTXT.setLayout(new java.awt.GridLayout(1, 0));

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jardimModelList, comboxAlterarIdJardim);
        bindingGroup.addBinding(jComboBoxBinding);

        painelTXT.add(comboxAlterarIdJardim);

        txtIdPlanta.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAlterar, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idPlanta}"), txtIdPlanta, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        painelTXT.add(txtIdPlanta);
        painelTXT.add(txtAlterarNome);
        painelTXT.add(txtAlterarTamanho);
        painelTXT.add(txtAlterarStatus);

        abaAlterar.add(painelTXT);
        painelTXT.setBounds(0, 470, 560, 40);

        lAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/salvar.png"))); // NOI18N
        lAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAtualizarMouseClicked(evt);
            }
        });
        abaAlterar.add(lAtualizar);
        lAtualizar.setBounds(450, 510, 110, 120);

        lMorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/morte.png"))); // NOI18N
        lMorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMorteMouseClicked(evt);
            }
        });
        abaAlterar.add(lMorte);
        lMorte.setBounds(20, 520, 100, 90);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        abaAlterar.add(jPanel2);
        jPanel2.setBounds(0, 560, 560, 30);

        txtExcluirIdPlanta.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAlterar, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idPlanta}"), txtExcluirIdPlanta, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        abaAlterar.add(txtExcluirIdPlanta);
        txtExcluirIdPlanta.setBounds(140, 440, 140, 30);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jardimModelList, comboxExcluirJardim);
        bindingGroup.addBinding(jComboBoxBinding);

        abaAlterar.add(comboxExcluirJardim);
        comboxExcluirJardim.setBounds(0, 440, 140, 30);

        txtExcluirNome.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAlterar, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), txtExcluirNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        abaAlterar.add(txtExcluirNome);
        txtExcluirNome.setBounds(280, 440, 140, 30);

        txtExcluirTamanho.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAlterar, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.tamanhoAtual}"), txtExcluirTamanho, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        abaAlterar.add(txtExcluirTamanho);
        txtExcluirTamanho.setBounds(420, 440, 140, 30);

        PainelGuias.addTab("Alterar", abaAlterar);

        abaExcluir.setLayout(null);

        lListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/salvar.png"))); // NOI18N
        lListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lListarMouseClicked(evt);
            }
        });
        abaExcluir.add(lListar);
        lListar.setBounds(450, 500, 100, 130);

        txtAreaLista.setEditable(false);
        txtAreaLista.setColumns(20);
        txtAreaLista.setRows(5);
        jScrollPane2.setViewportView(txtAreaLista);

        abaExcluir.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 560, 510);

        PainelGuias.addTab("Lista", abaExcluir);

        getContentPane().add(PainelGuias);
        PainelGuias.setBounds(0, 140, 570, 660);

        lHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/bt_Plantas.png"))); // NOI18N
        getContentPane().add(lHeader);
        lHeader.setBounds(0, 0, 570, 140);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    // BORBOLETA -- SALVAR
    private void lSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSalvarMouseClicked
        
        String nome = this.txtNome.getText();
        String tamanho = this.txtTamanho.getText();
        String status = this.comboxStatus.getSelectedItem().toString();
        Object jardim = this.comboxJardim.getSelectedItem();
        
        this.controller.cadastrarPlanta(nome, tamanho, status, (JardimModel) jardim);
        
    }//GEN-LAST:event_lSalvarMouseClicked

    // BORBOLETA -- ATUALIZAR
    private void lAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAtualizarMouseClicked
        
        String nome, status, tamanho; int idP;
            nome = this.txtAlterarNome.getText();
            tamanho = this.txtAlterarTamanho.getText();
            status = this.txtAlterarStatus.getText();
            idP = Integer.parseInt(this.txtIdPlanta.getText());
            Object idJardimbox = this.comboxAlterarIdJardim.getSelectedItem();   
          
        this.controller.atualizarPlanta(nome, tamanho, status, (JardimModel) idJardimbox, idP);
        
    }//GEN-LAST:event_lAtualizarMouseClicked

    // BORBOLETA -- LISTAR
    private void lListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lListarMouseClicked
  
        this.controller.consultaPlantas(txtAreaLista);
        
    }//GEN-LAST:event_lListarMouseClicked

    // TUMBA
    private void lMorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMorteMouseClicked
       
        Object obj; 
        int idP;
        JardimModel j = dao.em.find(JardimModel.class, 1);
        System.out.println(j);
        String nome, status, tamanho;
        nome = this.txtExcluirNome.getText();
        tamanho = this.txtExcluirTamanho.getText();
        status = "Falecida";
        idP = Integer.parseInt(this.txtExcluirIdPlanta.getText());
        
        this.controller.atualizarPlanta(nome, tamanho, status, j, idP);
        
    }//GEN-LAST:event_lMorteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlantaTela dialog = new PlantaTela(new javax.swing.JFrame(), true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager BabiloniaPersistenciaEntityManager;
    private javax.swing.JTabbedPane PainelGuias;
    private javax.swing.JPanel abaAlterar;
    private javax.swing.JPanel abaCadastrar;
    private javax.swing.JPanel abaExcluir;
    private javax.swing.JLabel bt1;
    private javax.swing.JLabel bt2;
    private javax.swing.JLabel bt3;
    private javax.swing.JLabel bt4;
    private javax.swing.JComboBox<String> comboxAlterarIdJardim;
    private javax.swing.JComboBox<String> comboxExcluirJardim;
    private javax.swing.JComboBox<String> comboxJardim;
    private javax.swing.JComboBox<String> comboxStatus;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAlterar;
    private java.util.List<br.maybueno.model.JardimModel> jardimModelList;
    private javax.persistence.Query jardimModelQuery;
    private javax.swing.JLabel lAtualizar;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel lHeader;
    private javax.swing.JLabel lJardim;
    private javax.swing.JLabel lListar;
    private javax.swing.JLabel lMorte;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lSalvar;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lTamanho;
    private javax.swing.JPanel painelTXT;
    private java.util.List<br.maybueno.view.Planta> plantaList;
    private java.util.List<br.maybueno.view.Planta> plantaList1;
    private java.util.List<br.maybueno.view.Planta> plantaList2;
    private java.util.List<br.maybueno.view.Planta> plantaList3;
    private javax.persistence.Query plantaQuery;
    private javax.persistence.Query plantaQuery1;
    private javax.persistence.Query plantaQuery2;
    private javax.persistence.Query plantaQuery3;
    private javax.swing.JTextField txtAlterarNome;
    private javax.swing.JTextField txtAlterarStatus;
    private javax.swing.JTextField txtAlterarTamanho;
    private javax.swing.JTextArea txtAreaLista;
    private javax.swing.JTextField txtExcluirIdPlanta;
    private javax.swing.JTextField txtExcluirNome;
    private javax.swing.JTextField txtExcluirTamanho;
    private javax.swing.JTextField txtIdPlanta;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTamanho;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
