package br.maybueno.view;
import br.maybueno.controller.JardimController;
import br.maybueno.dao.JardimDAO;

/**
 *
 * @author MayBueno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final long serialVersionUID = 4723651542090450943L;
    JardimController controller = new JardimController();
    
    /**
     * Creates new form JardimTela
     */
    public TelaPrincipal() {
        initComponents();       
        this.setTitle("Jardim Babilônia");
        
        String nome = "Jardim Celestial";
        String posicao = "Além";
        this.controller.criarJardimCelestial(nome, posicao);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BabiloniaPersistenciaEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("BabiloniaPersistencia").createEntityManager();
        jardimModelQuery = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT j FROM JardimModel j");
        jardimModelList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : jardimModelQuery.getResultList();
        plantaQuery = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery.getResultList();
        plantaQuery1 = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery1.getResultList();
        plantaQuery2 = java.beans.Beans.isDesignTime() ? null : BabiloniaPersistenciaEntityManager.createQuery("SELECT p FROM Planta p");
        plantaList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : plantaQuery2.getResultList();
        jPanel2 = new javax.swing.JPanel();
        lPlanta = new javax.swing.JLabel();
        lJardim = new javax.swing.JLabel();
        lFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 840));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        lPlanta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPlanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/bt_Jardim.png"))); // NOI18N
        lPlanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPlantaMouseClicked(evt);
            }
        });
        jPanel2.add(lPlanta);
        lPlanta.setBounds(0, 440, 570, 140);

        lJardim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lJardim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/bt_Plantas.png"))); // NOI18N
        lJardim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lJardimMouseClicked(evt);
            }
        });
        jPanel2.add(lJardim);
        lJardim.setBounds(0, 220, 570, 140);

        lFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/maybueno/img/bg01.png"))); // NOI18N
        jPanel2.add(lFundo);
        lFundo.setBounds(0, 0, 570, 800);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 570, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ABRIR TELA -- PLANTA_TELA
    private void lJardimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lJardimMouseClicked
       
        PlantaTela formP = new PlantaTela(this, true);
        formP.setTitle("Plantas");
        formP.setVisible(true);
       
        
    }//GEN-LAST:event_lJardimMouseClicked

    // ABRIR TELA -- JARDIM_TELA
    private void lPlantaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPlantaMouseClicked
        
        JardimTela formJ = new JardimTela(this, true);
        formJ.setTitle("Jardim");
        formJ.setVisible(true);
        
    }//GEN-LAST:event_lPlantaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager BabiloniaPersistenciaEntityManager;
    private javax.swing.JPanel jPanel2;
    private java.util.List<br.maybueno.model.JardimModel> jardimModelList;
    private javax.persistence.Query jardimModelQuery;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel lJardim;
    private javax.swing.JLabel lPlanta;
    private java.util.List<br.maybueno.view.Planta> plantaList;
    private java.util.List<br.maybueno.view.Planta> plantaList1;
    private java.util.List<br.maybueno.view.Planta> plantaList2;
    private javax.persistence.Query plantaQuery;
    private javax.persistence.Query plantaQuery1;
    private javax.persistence.Query plantaQuery2;
    // End of variables declaration//GEN-END:variables
}
